//! High-level Rust types that wrap the raw `vst3` crate FFI layer.
//!
//! Everything here is safe-Rust — where the underlying VST3 struct carries
//! FFI-only fields, we expose a newtype with accessor methods so downstream
//! code never needs to touch `unsafe`.

use std::ffi::c_void;

use smallvec::SmallVec;

mod audio;
mod events;
mod info;
mod params;
mod transport;

pub use audio::{AudioBuffer, BufferPtrs, Sample};
pub(crate) use audio::{K_SAMPLE_32_INT, K_SAMPLE_64_INT};
pub(crate) use events::{from_c_event, to_c_event};
pub use events::{
    vst3_event_from_midi, vst3_to_midi_event, vst3_to_note_expression, DataEvent, EventHeader,
    MidiEvent, NoteExpressionType, NoteExpressionValue, NoteExpressionValueEvent, NoteOffEvent,
    NoteOnEvent, PolyPressureEvent, Vst3Event, K_DATA_EVENT, K_NOTE_EXPRESSION_VALUE_EVENT,
    K_NOTE_OFF_EVENT, K_NOTE_ON_EVENT, K_POLY_PRESSURE_EVENT,
};
pub use info::{parameter_flags, BusInfo, Vst3ParameterInfo};
pub use params::{ParameterChanges, ParameterPoint, ParameterQueue};
pub use transport::TransportState;

/// Events and parameter changes emitted by the plugin during one call to
/// [`Vst3Instance::process`](crate::Vst3Instance::process).
pub struct ProcessOutput {
    /// MIDI events generated by the plugin (e.g. arpeggiator output).
    pub midi_events: SmallVec<[MidiEvent; 64]>,
    /// Parameter changes reported via `outputParameterChanges` — typically
    /// used by plugins with host-visible automation readouts.
    pub parameter_changes: ParameterChanges,
}

/// Pixel dimensions of a plugin editor window.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EditorSize {
    /// Width in pixels.
    pub width: u32,
    /// Height in pixels.
    pub height: u32,
}

/// A platform-specific parent window handle for embedding plugin editors.
///
/// Construct via [`WindowHandle::from_raw`], then pass to
/// [`Vst3Loaded::open_editor`](crate::Vst3Loaded::open_editor).
pub struct WindowHandle(*mut c_void);

impl WindowHandle {
    /// Wrap a raw platform window pointer.
    ///
    /// # Safety
    ///
    /// `ptr` must be a valid window handle for the current platform, and must
    /// remain valid for the lifetime of any editor attached to it:
    /// - **macOS:** `NSView*`
    /// - **Windows:** `HWND`
    /// - **Linux:** X11 window ID cast to pointer
    pub unsafe fn from_raw(ptr: *mut c_void) -> Self {
        Self(ptr)
    }

    pub(crate) fn as_ptr(&self) -> *mut c_void {
        self.0
    }
}

/// Identity + capability descriptor for a plugin class.
///
/// Populated by [`Vst3Loaded::probe`](crate::Vst3Loaded::probe) /
/// [`Vst3Loaded::load`](crate::Vst3Loaded::load); builder methods on this type
/// are exposed so hosts that wrap multiple plugin formats can construct
/// equivalent `PluginInfo` values by hand.
#[derive(Debug, Clone)]
pub struct PluginInfo {
    /// Unique id, formatted as `vst3.<CID>` by this crate.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Vendor / developer name.
    pub vendor: String,
    /// Plugin version string.
    pub version: String,
    /// Input channel count on bus 0.
    pub num_inputs: usize,
    /// Output channel count on bus 0.
    pub num_outputs: usize,
    /// `true` if the plugin exposes at least one input event bus.
    pub has_midi_input: bool,
    /// `true` if the plugin advertises `kSample64` processing.
    pub supports_f64: bool,
}

impl PluginInfo {
    /// Create a new descriptor with the minimum required fields; all other
    /// fields default to empty/false/stereo and can be set via the builder
    /// methods below.
    pub fn new(id: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            vendor: String::new(),
            version: String::new(),
            num_inputs: 2,
            num_outputs: 2,
            has_midi_input: false,
            supports_f64: false,
        }
    }

    /// Set the vendor field.
    pub fn vendor(mut self, vendor: impl Into<String>) -> Self {
        self.vendor = vendor.into();
        self
    }

    /// Set the version field.
    pub fn version(mut self, version: impl Into<String>) -> Self {
        self.version = version.into();
        self
    }

    /// Set input and output channel counts.
    pub fn audio_io(mut self, inputs: usize, outputs: usize) -> Self {
        self.num_inputs = inputs;
        self.num_outputs = outputs;
        self
    }

    /// Record whether this plugin receives MIDI.
    pub fn midi(mut self, has_midi: bool) -> Self {
        self.has_midi_input = has_midi;
        self
    }

    /// Record whether this plugin supports 64-bit float processing.
    pub fn f64_support(mut self, supports: bool) -> Self {
        self.supports_f64 = supports;
        self
    }
}
